### ISSUE TITLE
I am getting this error when I run the tool.

### ISSUE THREAD

**Issue by WellingtonMonteiro** [SASUKE-DUCK/AppleMusic-Downloader#5]
.____  _
   /   |  ____  ____  / /__     /  |/  /_  _______(_)____   / __ \(_)___  ____  ___  _____
  / /| | / __ \/ __ \/ / _ \   / /|_/ / / / / ___/ / ___/  / /_/ / / __ \/ __ \/ _ \/ ___/
 / ___ |/ /_/ / /_/ / /  __/  / /  / / /_/ (__  ) / /__   / _, _/ / /_/ / /_/ /  __/ /
/_/  |_/ .___/ .___/_/\___/  /_/  /_/\__,_/____/_/\___/  /_/ |_/_/ .___/ .___/\___/_/
      /_/   /_/                                                 /_/   /_/                                             

> REMAKE By ReiDoBregaBR
> SOURCE By Puyodead1
> VERSION 2.0.0

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AppleMusic-Downloader/applemusic.py", line 716, in <module>
    client = AppleMusicClient()
  File "/data/data/com.termux/files/home/AppleMusic-Downloader/applemusic.py", line 143, in __init__
    self.session = self.client_session()
  File "/data/data/com.termux/files/home/AppleMusic-Downloader/applemusic.py", line 229, in client_session
    "x-apple-music-user-token": self.session.cookies.get_dict()["media-user-token"],
KeyError: 'media-user-token'

**Comment by florinsdistortedvision** [comment]
you need to open music.apple.com, sign in (must have a subscription), then get your cookies using get cookies.txt extension and export it to /cookies/cookies.txt
